wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716031217.441713
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      3:
      - 23
      4: 3.11.2
      5: 0.16.1
      6: 4.35.0
      8:
      - 3
      - 5
      13: windows-amd64
